### ISSUE TITLE
Converting issue?

### ISSUE THREAD

**Issue by vicduncan** [Amir-Ashkezari/ACESConvertor#1]
When I try to convert any texture to ACEScg, it (input) always converts the color space to Utility - Log2 4000 nits Sharper AP1 which is incorrect.  What is the correct workflow when converting?  Do we set our color space to RAW or set it to its appropriate color space based on file extension?  Even when I set the color space to lets say Utility - sRGB - Texture, it changes it back to Log2 4000?  Cheers.

**Comment by Amir-Ashkezari** [comment]
What is the ACES version you are using? because the tool setting only works with ACES-1.2.

**Comment by vicduncan** [comment]
I am using ACES-1.2 the most current.  I am also doing test between this method and OCIO color space and that is the only issue when it converts.  Does the image need to be converted once read in?  Like if its a EXR does it need to be converted to Utility -Linear - sRGB first or set to Raw?

**Comment by Amir-Ashkezari** [comment]
No prior conversion will be needed, make sure OCIO env variable set correctly so Nuke can pick it up, nuke color management should be set to OCIO in the project settings.

**Comment by vicduncan** [comment]
Thank you for the response and yes all of my settings are correct and ocio (windows env var) and is my default setting within nuke.  I read in file by default is is recognized as Utility - sRGB - Texture, I select the read node a press A as the shortcut.  Boom the read node changes to Utility - Dolby PQ 4000 nits Sharper and writes that to ACEScg.  That is the issue... I think its a great tool to have which is why I want this to work on my end.

**Comment by Amir-Ashkezari** [comment]
Are you sure you are using the default OCIO.config? if so then please send me a sample image that you already test and it doesn't work for you so I can see if I encounter the same issue.

**Comment by Amir-Ashkezari** [comment]
Here is my email: amir.kh.ashkezari@gmail.com
